Gallery.examples = {"AR": {"title": "Analysis of An $AR(1)$ Model in pyMC3", "url": "/examples/../notebooks/AR.html", "thumb": "AR.png"}, "BEST": {"title": "Bayesian Estimation Supersedes the T-Test", "url": "/examples/../notebooks/BEST.html", "thumb": "BEST.png"}, "Bayes_factor": {"title": "Bayes Factors and Marginal Likelihood", "url": "/examples/../notebooks/Bayes_factor.html", "thumb": "Bayes_factor.png"}, "Diagnosing_biased_Inference_with_Divergences": {"title": "Diagnosing Biased Inference with Divergences", "url": "/examples/../notebooks/Diagnosing_biased_Inference_with_Divergences.html", "thumb": "Diagnosing_biased_Inference_with_Divergences.png"}, "Euler-Maruyama_and_SDEs": {"title": "Inferring parameters of SDEs using a Euler-Maruyama scheme", "url": "/examples/../notebooks/Euler-Maruyama_and_SDEs.html", "thumb": "Euler-Maruyama_and_SDEs.png"}, "GLM-hierarchical-advi-minibatch": {"title": "GLM: Mini-batch ADVI on hierarchical regression model", "url": "/examples/../notebooks/GLM-hierarchical-advi-minibatch.html", "thumb": "GLM-hierarchical-advi-minibatch.png"}, "GLM-hierarchical-binominal-model": {"title": "Hierarchical Binominal Model: Rat Tumor Example", "url": "/examples/../notebooks/GLM-hierarchical-binominal-model.html", "thumb": "GLM-hierarchical-binominal-model.png"}, "GLM-hierarchical": {"title": "GLM: Hierarchical Linear Regression", "url": "/examples/../notebooks/GLM-hierarchical.html", "thumb": "GLM-hierarchical.png"}, "GLM-linear": {"title": "GLM: Linear regression", "url": "/examples/../notebooks/GLM-linear.html", "thumb": "GLM-linear.png"}, "GLM-logistic": {"title": "GLM: Logistic Regression", "url": "/examples/../notebooks/GLM-logistic.html", "thumb": "GLM-logistic.png"}, "GLM-model-selection": {"title": "GLM: Model Selection", "url": "/examples/../notebooks/GLM-model-selection.html", "thumb": "GLM-model-selection.png"}, "GLM-negative-binomial-regression": {"title": "GLM: Negative Binomial Regression", "url": "/examples/../notebooks/GLM-negative-binomial-regression.html", "thumb": "GLM-negative-binomial-regression.png"}, "GLM-poisson-regression": {"title": "GLM: Poisson Regression", "url": "/examples/../notebooks/GLM-poisson-regression.html", "thumb": "GLM-poisson-regression.png"}, "GLM-robust-with-outlier-detection": {"title": "GLM: Robust Regression with Outlier Detection", "url": "/examples/../notebooks/GLM-robust-with-outlier-detection.html", "thumb": "GLM-robust-with-outlier-detection.png"}, "GLM-robust": {"title": "GLM: Robust Linear Regression", "url": "/examples/../notebooks/GLM-robust.html", "thumb": "GLM-robust.png"}, "GLM-rolling-regression": {"title": "Rolling Regression", "url": "/examples/../notebooks/GLM-rolling-regression.html", "thumb": "GLM-rolling-regression.png"}, "GLM": {"title": "GLM: Linear Regression", "url": "/examples/../notebooks/GLM.html", "thumb": "GLM.png"}, "GP-Kron": {"title": "Kronecker Structured Covariances", "url": "/examples/../notebooks/GP-Kron.html", "thumb": "GP-Kron.png"}, "GP-Latent": {"title": "Latent Variable Implementation", "url": "/examples/../notebooks/GP-Latent.html", "thumb": "GP-Latent.png"}, "GP-Marginal": {"title": "Marginal Likelihood Implementation", "url": "/examples/../notebooks/GP-Marginal.html", "thumb": "GP-Marginal.png"}, "GP-MaunaLoa": {"title": "Example: CO2 at Mauna Loa", "url": "/examples/../notebooks/GP-MaunaLoa.html", "thumb": "GP-MaunaLoa.png"}, "GP-MaunaLoa2": {"title": "Example:  Mauna Loa CO$_2$ continued", "url": "/examples/../notebooks/GP-MaunaLoa2.html", "thumb": "GP-MaunaLoa2.png"}, "GP-MeansAndCovs": {"title": "Mean and Covariance Functions", "url": "/examples/../notebooks/GP-MeansAndCovs.html", "thumb": "GP-MeansAndCovs.png"}, "GP-SparseApprox": {"title": "Sparse Approximations", "url": "/examples/../notebooks/GP-SparseApprox.html", "thumb": "GP-SparseApprox.png"}, "GP-TProcess": {"title": "Student-t Process", "url": "/examples/../notebooks/GP-TProcess.html", "thumb": "GP-TProcess.png"}, "GP-slice-sampling": {"title": "Gaussian Process Regression and Classification with Elliptical Slice Sampling", "url": "/examples/../notebooks/GP-slice-sampling.html", "thumb": "GP-slice-sampling.png"}, "GP-smoothing": {"title": "Gaussian Process (GP) smoothing", "url": "/examples/../notebooks/GP-smoothing.html", "thumb": "GP-smoothing.png"}, "LKJ": {"title": "LKJ Cholesky Covariance Priors for Multivariate Normal Models", "url": "/examples/../notebooks/LKJ.html", "thumb": "LKJ.png"}, "MvGaussianRandomWalk_demo": {"title": "MvGaussianRandomWalk demo.ipynb", "url": "/examples/../notebooks/MvGaussianRandomWalk_demo.html", "thumb": "MvGaussianRandomWalk_demo.png"}, "PyMC3_tips_and_heuristic": {"title": "PyMC3 Modeling tips and heuristic", "url": "/examples/../notebooks/PyMC3_tips_and_heuristic.html", "thumb": "PyMC3_tips_and_heuristic.png"}, "SMC2_gaussians": {"title": "Sequential Monte Carlo with two gaussians", "url": "/examples/../notebooks/SMC2_gaussians.html", "thumb": "SMC2_gaussians.png"}, "api_quickstart": {"title": "API quickstart", "url": "/examples/../notebooks/api_quickstart.html", "thumb": "api_quickstart.png"}, "bayes_param_survival_pymc3": {"title": "Bayesian Parametric Survival Analysis with PyMC3", "url": "/examples/../notebooks/bayes_param_survival_pymc3.html", "thumb": "bayes_param_survival_pymc3.png"}, "bayesian_neural_network_advi": {"title": "Variational Inference: Bayesian Neural Networks", "url": "/examples/../notebooks/bayesian_neural_network_advi.html", "thumb": "bayesian_neural_network_advi.png"}, "bayesian_neural_network_with_sgfs": {"title": "Bayesian Neural Networks in PyMC3 with Stochastic Gradient Algorithms", "url": "/examples/../notebooks/bayesian_neural_network_with_sgfs.html", "thumb": "bayesian_neural_network_with_sgfs.png"}, "blackbox_external_likelihood": {"title": "Using a \"black box\" likelihood function", "url": "/examples/../notebooks/blackbox_external_likelihood.html", "thumb": "blackbox_external_likelihood.png"}, "censored_data": {"title": "Censored Data Models", "url": "/examples/../notebooks/censored_data.html", "thumb": "censored_data.png"}, "constant_stochastic_gradient": {"title": "Constant Stochastic Gradient", "url": "/examples/../notebooks/constant_stochastic_gradient.html", "thumb": "constant_stochastic_gradient.png"}, "convolutional_vae_keras_advi": {"title": "Convolutional variational autoencoder with PyMC3 and Keras", "url": "/examples/../notebooks/convolutional_vae_keras_advi.html", "thumb": "convolutional_vae_keras_advi.png"}, "cox_model": {"title": "Set up data", "url": "/examples/../notebooks/cox_model.html", "thumb": "cox_model.png"}, "dawid-skene": {"title": "The Dawid-Skene model with priors", "url": "/examples/../notebooks/dawid-skene.html", "thumb": "dawid-skene.png"}, "dependent_density_regression": {"title": "Dependent density regression", "url": "/examples/../notebooks/dependent_density_regression.html", "thumb": "dependent_density_regression.png"}, "dp_mix": {"title": "Dirichlet process mixtures for density estimation", "url": "/examples/../notebooks/dp_mix.html", "thumb": "dp_mix.png"}, "empirical-approx-overview": {"title": "Empirical Approximation overview", "url": "/examples/../notebooks/empirical-approx-overview.html", "thumb": "empirical-approx-overview.png"}, "gaussian-mixture-model-advi": {"title": "Gaussian Mixture Model with ADVI", "url": "/examples/../notebooks/gaussian-mixture-model-advi.html", "thumb": "gaussian-mixture-model-advi.png"}, "gaussian_mixture_model": {"title": "Gaussian Mixture Model", "url": "/examples/../notebooks/gaussian_mixture_model.html", "thumb": "gaussian_mixture_model.png"}, "gaussian_process": {"title": "Gaussian Processes", "url": "/examples/../notebooks/gaussian_process.html", "thumb": "gaussian_process.png"}, "getting_started": {"title": "Getting started with PyMC3", "url": "/examples/../notebooks/getting_started.html", "thumb": "getting_started.png"}, "hierarchical_partial_pooling": {"title": "Hierarchical Partial Pooling", "url": "/examples/../notebooks/hierarchical_partial_pooling.html", "thumb": "hierarchical_partial_pooling.png"}, "howto_debugging": {"title": "How to debug a model", "url": "/examples/../notebooks/howto_debugging.html", "thumb": "howto_debugging.png"}, "lasso_block_update": {"title": "Lasso regression with block updating", "url": "/examples/../notebooks/lasso_block_update.html", "thumb": "lasso_block_update.png"}, "lda-advi-aevb": {"title": "Automatic autoencoding variational Bayes for latent dirichlet allocation with PyMC3", "url": "/examples/../notebooks/lda-advi-aevb.html", "thumb": "lda-advi-aevb.png"}, "live_sample_plots": {"title": "Live sample plots", "url": "/examples/../notebooks/live_sample_plots.html", "thumb": "live_sample_plots.png"}, "marginalized_gaussian_mixture_model": {"title": "Marginalized Gaussian Mixture Model", "url": "/examples/../notebooks/marginalized_gaussian_mixture_model.html", "thumb": "marginalized_gaussian_mixture_model.png"}, "model_averaging": {"title": "Model averaging", "url": "/examples/../notebooks/model_averaging.html", "thumb": "model_averaging.png"}, "model_comparison": {"title": "Model comparison", "url": "/examples/../notebooks/model_comparison.html", "thumb": "model_comparison.png"}, "multilevel_modeling": {"title": "A Primer on Bayesian Methods for Multilevel Modeling", "url": "/examples/../notebooks/multilevel_modeling.html", "thumb": "multilevel_modeling.png"}, "normalizing_flows_overview": {"title": "Normalizing Flows Overview", "url": "/examples/../notebooks/normalizing_flows_overview.html", "thumb": "normalizing_flows_overview.png"}, "posterior_predictive": {"title": "Posterior Predictive Checks", "url": "/examples/../notebooks/posterior_predictive.html", "thumb": "posterior_predictive.png"}, "profiling": {"title": "profiling.ipynb", "url": "/examples/../notebooks/profiling.html", "thumb": "profiling.png"}, "rugby_analytics": {"title": "A Hierarchical model for Rugby prediction", "url": "/examples/../notebooks/rugby_analytics.html", "thumb": "rugby_analytics.png"}, "sampler-stats": {"title": "Sampler statistics", "url": "/examples/../notebooks/sampler-stats.html", "thumb": "sampler-stats.png"}, "sampling_compound_step": {"title": "Compound Steps in Sampling", "url": "/examples/../notebooks/sampling_compound_step.html", "thumb": "sampling_compound_step.png"}, "sgfs_simple_optimization": {"title": "Stochastic Gradient Fisher Scoring", "url": "/examples/../notebooks/sgfs_simple_optimization.html", "thumb": "sgfs_simple_optimization.png"}, "stochastic_volatility": {"title": "Stochastic Volatility model", "url": "/examples/../notebooks/stochastic_volatility.html", "thumb": "stochastic_volatility.png"}, "survival_analysis": {"title": "Bayesian Survival Analysis", "url": "/examples/../notebooks/survival_analysis.html", "thumb": "survival_analysis.png"}, "updating_priors": {"title": "Updating priors", "url": "/examples/../notebooks/updating_priors.html", "thumb": "updating_priors.png"}, "variational_api_quickstart": {"title": "Variational API quickstart", "url": "/examples/../notebooks/variational_api_quickstart.html", "thumb": "variational_api_quickstart.png"}, "weibull_aft": {"title": "Reparameterizing the Weibull Accelerated Failure Time Model", "url": "/examples/../notebooks/weibull_aft.html", "thumb": "weibull_aft.png"}}
Gallery.contents = {
    "AR": "Time Series",
    "BEST": "Applied",
    "Bayes_factor": "Other",
    "Diagnosing_biased_Inference_with_Divergences": "Diagnostics",
    "Euler-Maruyama_and_SDEs": "Time Series",
    "GLM-hierarchical-advi-minibatch": "Variational Inference",
    "GLM-hierarchical-binominal-model": "GLMs",
    "GLM-hierarchical": "GLMs",
    "GLM-linear": "GLMs",
    "GLM-logistic": "GLMs",
    "GLM-model-selection": "GLMs",
    "GLM-negative-binomial-regression": "GLMs",
    "GLM-poisson-regression": "GLMs",
    "GLM-robust-with-outlier-detection": "GLMs",
    "GLM-robust": "GLMs",
    "GLM-rolling-regression": "GLMs",
    "GLM": "GLMs",
    "GP-Kron": "Gaussian Processes",
    "GP-Latent": "Gaussian Processes",
    "GP-Marginal": "Gaussian Processes",
    "GP-MaunaLoa": "Gaussian Processes",
    "GP-MaunaLoa2": "Gaussian Processes",
    "GP-MeansAndCovs": "Gaussian Processes",
    "GP-SparseApprox": "Gaussian Processes",
    "GP-TProcess": "Gaussian Processes",
    "GP-slice-sampling": "Gaussian Processes",
    "GP-smoothing": "Gaussian Processes",
    "LKJ": "How-To",
    "MvGaussianRandomWalk_demo": "Time Series",
    "PyMC3_tips_and_heuristic": "How-To",
    "SMC2_gaussians": "Other",
    "api_quickstart": "How-To",
    "bayes_param_survival_pymc3": "Survival Analysis",
    "bayesian_neural_network_advi": "Variational Inference",
    "bayesian_neural_network_with_sgfs": "Stochastic Gradients",
    "blackbox_external_likelihood": "How-To",
    "censored_data": "Survival Analysis",
    "constant_stochastic_gradient": "Stochastic Gradients",
    "convolutional_vae_keras_advi": "Variational Inference",
    "cox_model": "Other",
    "dawid-skene": "Applied",
    "dependent_density_regression": "Mixture Models",
    "dp_mix": "Mixture Models",
    "empirical-approx-overview": "Variational Inference",
    "gaussian-mixture-model-advi": "Mixture Models",
    "gaussian_mixture_model": "Mixture Models",
    "gaussian_process": "Gaussian Processes",
    "getting_started": "How-To",
    "hierarchical_partial_pooling": "GLMs",
    "howto_debugging": "How-To",
    "lasso_block_update": "How-To",
    "lda-advi-aevb": "Variational Inference",
    "live_sample_plots": "How-To",
    "marginalized_gaussian_mixture_model": "Mixture Models",
    "model_averaging": "How-To",
    "model_comparison": "Diagnostics",
    "multilevel_modeling": "Applied",
    "normalizing_flows_overview": "Variational Inference",
    "posterior_predictive": "Diagnostics",
    "profiling": "How-To",
    "rugby_analytics": "Applied",
    "sampler-stats": "How-To",
    "sampling_compound_step": "How-To",
    "sgfs_simple_optimization": "Stochastic Gradients",
    "stochastic_volatility": "Applied",
    "survival_analysis": "Survival Analysis",
    "updating_priors": "How-To",
    "variational_api_quickstart": "Variational Inference",
    "weibull_aft": "Survival Analysis"
}
